language:
  - c

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - p7zip-full
      - realpath

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew bundle; fi

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure

