#!/usr/bin/env bash

# 7zdec
#
# Copyright (c) 2015, Kristofer Berggren
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the author nor the names of its contributors may
#       be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Package details ####################################################
URL="https://github.com/d99kris/7zetools"
PKGNAME="7zetools"
VERSION="1.01"
PROGNAME="7zdec"
AUTHOR="Kristofer Berggren"

# Pre-requisites checking ############################################
which 7z &> /dev/null
if [ "${?}" != "0" ]; then
  echo "Required tool 7z not found."
  exit 1
fi
TMPDIR="/dev/shm"
if [[ ! -d "${TMPDIR}" ]]; then
  if [[ "$(uname)" == "Darwin" ]]; then
    TMPDIR="/Volumes/7zetools"
  else
    echo "Required directory ${TMPDIR} not found, exiting."
    exit 1
  fi
fi

# Globals ############################################################
USERTMPDIR="${TMPDIR}/7z-`whoami`"
USERPASSFILE="${USERTMPDIR}/password"

# Application info ###################################################
showusage()
{
  echo "${PROGNAME} decrypts specified 7z archive, using the encryption"
  echo "key set up using 7zpass. The decrypted files/directories are written"
  echo "to current directory."
  echo ""
  echo "Usage: ${PROGNAME} OPTION"
  echo "   or: ${PROGNAME} PATH"
  echo ""
  echo "Options:"
  echo "   --help        display this help and exit"
  echo "   --version     output version information and exit"
  echo "   PATH          7z archive file to decrypt"
  echo ""
  echo "Examples:"
  echo "   ${PROGNAME} a.7z    decrypts and extracts the content"
  echo "                 of a.7z to current directory."
  echo ""
  echo "Report bugs at ${URL}"
  echo ""
}

showversion()
{
  echo "${PROGNAME} v${VERSION}"
  echo ""
  echo "Copyright (C) 2015 ${AUTHOR}"
  echo ""
  echo "${PROGNAME} is part of 7zetools and distributed"
  echo "under BSD 3-Clause license."
  echo ""
  echo "Written by ${AUTHOR}"
}

# Usage checking #####################################################
if [ "${1}" == "--help" ] ; then
  showusage
  exit 0
elif [ "${1}" == "--version" ] ; then
  showversion
  exit 0
elif [ "${#}" != "1" ] ; then
  showusage
  exit 1
else
  ENCPATH="${1}"
fi

# Password checking ##################################################
if [ -f "${USERPASSFILE}" ]; then
  KEY1="`cat ${USERPASSFILE}`"
fi
if [ "${KEY1}" == "" ]; then
  echo "Password is not set, please run 7zpass to set password"
  exit 1
fi

# Decrypt specified file #############################################
7z x -p${KEY1} ${ENCPATH}

# Exit ###############################################################
exit 0

